allowBuilds:
  '@newrelic/fn-inspect': set this to true or false
  '@newrelic/native-metrics': set this to true or false
  '@scarf/scarf': set this to true or false
  '@sentry-internal/node-cpu-profiler': set this to true or false
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  protobufjs: set this to true or false
