/**
 * Generate TypeScript types from the OpenAPI spec.
 * Run from backend: npm run sdk:generate
 *
 * Outputs to: frontend/src/api/generated/api.d.ts
 *
 * Requires openapi-typescript to be installed:
 *   npm install -D openapi-typescript
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import openapiTS, { astToString } from 'openapi-typescript'
import spec from '../src/openapi/spec.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outDir = resolve(__dirname, '..', '..', 'frontend', 'src', 'api', 'generated')
const outPath = join(outDir, 'api.d.ts')

mkdirSync(outDir, { recursive: true })

// openapi-typescript accepts a parsed OpenAPI object directly
const ast = await openapiTS(spec as Parameters<typeof openapiTS>[0])
const contents = astToString(ast)

writeFileSync(
    outPath,
    [
        '// This file is auto-generated by `npm run sdk:generate`.',
        '// Do not edit manually — run the script to regenerate.',
        '',
        contents,
    ].join('\n'),
)

console.log('TypeScript SDK types generated at:', outPath)
